// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	database "github.com/karamaru-alpha/melt/pkg/domain/database"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ValidateUserName mocks base method.
func (m *MockService) ValidateUserName(ctx context.Context, tx database.Tx, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserName", ctx, tx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUserName indicates an expected call of ValidateUserName.
func (mr *MockServiceMockRecorder) ValidateUserName(ctx, tx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserName", reflect.TypeOf((*MockService)(nil).ValidateUserName), ctx, tx, name)
}
