// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	user2 "github.com/karamaru-alpha/melt/pkg/api/handler/user"
	"github.com/karamaru-alpha/melt/pkg/api/usecase/user"
	"github.com/karamaru-alpha/melt/pkg/domain/proto/api"
	"github.com/karamaru-alpha/melt/pkg/infra/mysql"
	"github.com/karamaru-alpha/melt/pkg/infra/mysql/repository"
	"github.com/karamaru-alpha/melt/pkg/util"
)

// Injectors from wire.go:

func DI() proto.UserServer {
	ulidGenerator := util.NewUILDGenerator()
	db := mysql.New()
	userRepository := repository.NewUserRepository(db)
	txManager := mysql.NewDBTxManager(db)
	interactor := user.New(ulidGenerator, userRepository, txManager)
	userServer := user2.New(interactor)
	return userServer
}
