// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	auth2 "github.com/karamaru-alpha/melt/pkg/api/handler/auth"
	"github.com/karamaru-alpha/melt/pkg/api/usecase/auth"
	"github.com/karamaru-alpha/melt/pkg/domain/proto/api"
	"github.com/karamaru-alpha/melt/pkg/infra/mysql"
	"github.com/karamaru-alpha/melt/pkg/infra/mysql/repository"
	"github.com/karamaru-alpha/melt/pkg/util"
)

// Injectors from wire.go:

func DI() api.AuthServer {
	ulidGenerator := util.NewUILDGenerator()
	db := mysql.New()
	userRepository := repository.NewUserRepository(db)
	txManager := mysql.NewDBTxManager(db)
	interactor := auth.New(ulidGenerator, userRepository, txManager)
	authServer := auth2.New(interactor)
	return authServer
}
